version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dev_news_aggregator_development
      POSTGRES_USER: dev_news_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_news_user -d dev_news_aggregator_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://dev_news_user:dev_password@db:5432/dev_news_aggregator_development

volumes:
  postgres_data:
